#+title: Active Onboarding
#+date: 2023-03-29

Having recently changed jobs, I had the pleasure of onboarding for the
first time in four years again, definitely a change of pace. Being
quite senior at this point, I have been worrying a bit about how to
join a new organisation and perform on my level, not having benefited
from working directly on the ground for a long time, thus lacking
direct technical experience and also social legitimacy.

Also joining a smaller but actively growing organisation, I expected
there not to be a lot of structured onboarding process or
guidance,[fn:1] so I decided to take some ownership of the process
ahead of time.

[fn:1] Even organisations multiple times the size of this one had very
little in the form of onboarding material, and I would be proven right
this time as well.

* Take Notes

Frequent readers of this site will not be surprised that I advocate
for [[https://www.youtube.com/watch?v=1PENZkWqqUk][writing things down]]. Not only will there be a lot of new
information during the first few weeks that will be difficult to
retain, people, services, processes, and so on, but also observations
about the onboarding process itself.

I make it a habit to note down any stumbling blocks I encounter, such
as access I have not been granted, or documentation that was missing.
These notes are invaluable to improve the onboarding process for
future joiners.

* Capitalise on Those Fresh Eyes

Generally speaking, one is joining an existing organisation from a
different context, mostly that of ones previous organisation, maybe
also the one before that. This means the circumstances that seem
normal and ordinary to everyone else can be contrasted against that
prior context, a great starting point to question the status quo.
Sometimes there have been conscious, valid decisions that led to it,
but sometimes these decisions did not stand the test of time, and even
more often, there were no conscious decisions, and the status quo just
exists because no one was aware of the alternatives.[fn:2]

[fn:2] Of course things can also be surprisingly better than one is
used to, and that's worth noting down as well for future reference, or
to explicitly hold on to, but in my experience negatives tend to stick
out more during first encounters.

* Prepare a Plan

I had the luxury of taking a few weeks off in between jobs, which was
great for some unwinding, but also gave me some time to come up with a
plan for the new job. I started looking at the tech I knew they were
using but I was not familiar with yet/anymore, and also prepared a
very rough list of goals for my first 30 days. This might sound a bit
heavy-handed, but it really just boiled down to:

1. Agree with my manager on a job description and expectations.
2. Identify and meet with as many key people as I can, both
   directors, VPs, and executives, as well as managers, team leads,
   and product owners in various adjacent domains.
3. Fill out a list of questions to answer about the current state of
   things. I stole a large chunk of this from a VP at my last
   organisation, and a lot of this is quite fundamental, but still a
   good guideline. Some examples:[fn:3]
   - What is our mission/vision/problem solved?
   - What is the competetive landscape like?
   - What happened over the last year?
   - What are we planning over the next year?
   - What have been the best decisions so far?
   - What have been the worst decisions so far?
   - What is the organisational structure?
   - What is the technical architecture?
   - How are decisions made at different levels?
4. Share the results of the survey with everyone else to spark some
   conversation, and also come up with my own hypothesis of where I
   can be useful.

[fn:3] There are around 200 questions in the actual list, but a lot of
them are much more fine-grained, such as "who owns uptime?" or "how is
test coverage?" I use these questions during my first (and second)
meetings with new colleagues, which give me an automatic agenda past
the self-introduction, and can be useful to see how people in
different positions think about the state of the organisation. If
you're interested in the full list get in touch, and I can prepare an
anonymised version of it.

* Keep an Open Mind

Especially during my first month I am expecting to just soak up
information by asking questions and listening to what is said and what
is left unsaid. This helps to disconnect from preconceived notions
about how an organisation ought to work, because there is no
one-size-fits-all approach anyway.

Last but not least, coming in very strong might be acceptable, or even
expected from, a new VP or executive, but on a staff engineer level it
is an easy way to make enemies within the first few weeks. Things will
be different from what one is used to, and in some ways probably for
the worse, but such is life.
