image: haskell:latest

before_script:
  - apt-get update -y && apt-get install -y xz-utils make texlive-xetex
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
  - stack build

build:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec blog build
  except:
    - develop

pages:
  cache:
    paths:
      - _cache
      - .stack
  script:
    - stack exec blog build
  artifacts:
    paths:
      - _site
  only:
    - develop
