image: haskell:latest

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt-get update -y && apt-get install -y xz-utils make texlive-xetex
  - export STACK_ROOT=`pwd`/.stack
  - stack setup
  - stack install --only-dependencies
  - stack build

pages:
  cache:
    paths:
      - _cache
      - .stack
      - .stack-work
  script:
    - stack exec blog build && mv _site public
  artifacts:
    paths:
      - public
  only:
    - develop
