[site]
title = "sulami's blog"
description = "Weak Opinions, Strongly Held"
author = "Robin Schroer"
email = "blog@sulami.xyz"
url = "https://blog.sulami.xyz"
code_theme = "Solarized (light)"

[[site.menu]]
title = "Feed"
link = "virtual:feed"

[[site.menu]]
title = "About"
link = "file:input/content/about.md"
