[site]
title = "Weak Opinions, Strongly Held"
author = "Robin Schroer"
email = "blog@sulami.xyz"
url = "https://blog.sulami.xyz"
code_theme = "Solarized (light)"

[[site.menu]]
title = "Feed"
link = "input/content/atom.xml"

[[site.menu]]
title = "Now"
link = "input/content/now.md"

[[site.menu]]
title = "Uses"
link = "input/content/uses.md"

[[site.menu]]
title = "About"
link = "input/content/about.md"
