version: 2.1

orbs:
  s3: circleci/aws-s3@4.0.0
  aws: circleci/aws-cli@4.1.3

jobs:
  build:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ checksum "Cargo.lock" }}
      - run:
          name: Compile binary
          command: cargo build
      - save_cache:
          key: v2-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
      - run:
          name: Render output
          command: target/debug/blog render
      - store_artifacts:
          path: output
          destination: '.'
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - aws/setup
            - s3/sync:
                from: output
                to: s3://blog.sulami.xyz
                arguments: '--delete'
            - run:
                name: Invalidate CloudFront
                command: aws cloudfront create-invalidation --distribution=E26ZR38R58OFSG --paths "/*"

workflows:
  build-and-deploy:
    jobs:
      - build
