version: 2.1

orbs:
  s3: circleci/aws-s3@3.1.1

jobs:
  build:
    docker:
      - image: silex/emacs:27-ci
    steps:
      - checkout
      - run:
          name: Deep checkout
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Install LaTeX
          command: |
            apt update
            apt install -y locales texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - restore_cache:
          key: v1-{{ checksum "deps.el" }}
      - run:
          name: Render output
          command: |
            export CI_PWD=$(pwd)
            emacs --batch \
                -l config.el \
                --eval "(blog/render-all)"
      - save_cache:
          key: v1-{{ checksum "deps.el" }}
          paths:
            - '~/.emacs.d'
      - store_artifacts:
          path: _site
          destination: '.'
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - s3/sync:
                from: _site
                to: s3://blog.sulami.xyz
                arguments: '--delete'

workflows:
  build-and-deploy:
    jobs:
      - build
