version: 2.1

jobs:
  build:
    docker:
      - image: silex/emacs:27-ci
    steps:
      - checkout
      - run:
          name: Deep checkout
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Install LaTeX
          command: |
            apt update
            apt install -y locales texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra
      - restore_cache:
          key: v1-{{ checksum "deps.el" }}
      - run:
          name: Render output
          command: |
            export CI_PWD=$(pwd)
            emacs --batch \
                -l config.el \
                --eval "(org-publish \"website\" t)"
      - save_cache:
          key: v1-{{ checksum "deps.el" }}
          paths:
            - '~/.emacs.d'
      - persist_to_workspace:
          root: .
          paths:
            - _site
      - store_artifacts:
          path: _site
          destination: '.'

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: _site
      - run: |
          cd _site
          git checkout master
          git pull origin master:master
      - attach_workspace:
          at: .
      - run: |
          cd _site
          git add -A
          git config user.email "blog@sulami.xyz"
          git config user.name "Robin Schroer"
          git commit -m "[skip ci] Publish."
          git push -q << pipeline.project.git_url >>.git master:master

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
