version: 2.1

orbs:
  s3: circleci/aws-s3@3.1.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.75
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "Cargo.lock" }}-{{ checksum "src" }}
      - run:
          name: Compile binary
          command: cargo build --release
      - save_cache:
          key: v1-{{ checksum "Cargo.lock" }}-{{ checksum "src" }}
          paths:
            - "target"
      - run:
          name: Render output
          command: target/release/blog render
      - store_artifacts:
          path: output
          destination: '.'
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - s3/sync:
                from: _site
                to: s3://blog.sulami.xyz
                arguments: '--delete'

workflows:
  build-and-deploy:
    jobs:
      - build
