version: 2.1

jobs:
  build:
    docker:
      - image: haskell:8
    environment:
      DEBIAN_FRONTEND: noninteractive
      LANGUAGE: C
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          apt update
          apt install -y locales texlive-latex-base texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra racket
      - restore_cache:
          name: Restoring GHC cache
          key: v2-ghc-{{ checksum "stack.yaml" }}
      - run: stack --no-terminal setup
      - save_cache:
          name: Saving GHC cache
          key: v2-ghc-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      - restore_cache:
          name: Restoring Stack cache
          keys:
            - v2-bin-{{ checksum "stack.yaml" }}-{{ checksum "blog.cabal" }}-{{ checksum "site.hs" }}
            - v2-deps-{{ checksum "stack.yaml" }}-{{ checksum "blog.cabal" }}
      - run: stack --no-terminal install --only-dependencies
      - save_cache:
          name: Saving Stack dependencies cache
          key: v2-deps-{{ checksum "stack.yaml" }}-{{ checksum "blog.cabal" }}
          paths:
            - .stack-work
            - ~/.stack
            - ~/.local/bin
      - run: stack --no-terminal build
      - save_cache:
          name: Saving Stack binary cache
          key: v2-bin-{{ checksum "stack.yaml" }}-{{ checksum "blog.cabal" }}-{{ checksum "site.hs" }}
          paths:
            - .stack-work
            - ~/.stack
            - ~/.local/bin
      - run: raco pkg install --batch --deps search-auto threading
      - run: racket export-metadata.rkt
      - run: stack exec --no-terminal blog build
      - persist_to_workspace:
          root: .
          paths:
            - _site

  deploy:
    docker:
      - image: haskell:8
    steps:
      - checkout:
          path: _site
      - run: |
          cd _site
          git checkout master
      - attach_workspace:
          at: .
      - run: |
          cd _site
          git add -A
          git commit -m "Publish."
          git push origin master:master
      - store_artifacts:
          path: _site

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
