#+title: Being a Journalist Within Your Organisation
#+date: 2023-01-07

Having been a staff+ engineer located in Europe while working at a
primarily North-American company last year, one piece of feedback I
regularly got was that I seemed to know about many things happening,
but many folks in my domain who got less synchronous time with me felt
like they could not benefit from that. The teams I was directly
working with were split roughly 60-40 between North America (East
coast) and Europe, so more than half of the team members only
overlapped with me during my already busy afternoons.

An important part of staff+ engineering is to figure out the best way
to utilise the limited available, Will Larson [[https://lethain.com/work-on-what-matters/][has written]] a lot about
how to chose the right work. Thinking about the personal feedback I
had gotten, and also wider organisational problems we were facing,
such as a tendency to misalign or duplicate work, I realised there was
something simple I could do in my corner of the organisation that
promised large returns for a small time investment: I started a work
blog.

Blog is a big word for what it turned out to be, maybe more fitting
would be a weekly digest. I started chronicling what I had been
thinking about, investigating, or prototyping, what teams in my domain
were working on, what decisions or plans were being made, and what
work had been completed (or sometimes abandoned). There was no fixed
structure, just a list of bullet points with a descriptive heading and
0-3 sentences of details and links.

I would gather items for the digest during the week, and then spend a
few minutes organising and polishing them on Monday mornings[fn:1] for
publishing. The bar for something to make the digest was quite low,
after all not that much is really happening in a domain, and the point
of this is to share the kind of information that would usually be
exchanged at a water cooler.[fn:2] It is effectively a form of working
in the open. Each week usually had four to six items.

Another aspect here is getting more folks insight into what happens in
[[https://lethain.com/getting-in-the-room/][the room]]. Some things that happen in the room can be sensitive, or are
better kept quiet for a while, but many things are just never shared
because no one can be bothered to share them.[fn:3] This is especially
frustrating for folks trying to make it to a level (often staff+) to
get into the room, but cannot prove their worth without having access
to the room first.

Coming back to picking the best use of time, one could try to
personally distribute the same information to selected individuals,
but broadcasting is inherently more scalable as it requires constant
effort regardless of the size of the audience. My usual time spent per
week was somewhere around five minutes. If a few people from different
areas of the organisation take up this habit, a small[fn:4] collection of
digests can develop which can drive alignment and help new joiners
understand what is going on more quickly.

From a practical perspective, senior leaders like to write email
newsletters, with varying degrees of usefulness in my experience, and
this is similar but less focused on business plans (or making a
department look good) and more of a front report. I ended up using
Confluence's blog feature for this, which allows others to subscribe
to updates, but automatically creates a browsable archive as well,
which I find highly useful for identifying patterns or areas worth
investing into. I would also post updates to Slack to raise awareness.

I will continue to use this method, and I recommend you give it a try
too.

[fn:1] EU Monday mornings meant that everyone besides APAC got to
start their week reading the digest, which I think is a good time.
Information taken in on Friday afternoons is difficult to retain.

[fn:2] Think "Oh, you're doing X? That is going to be a problem for
Y." or "I see you're thinking about X, but we're doing Y which will be
much easier for you."

[fn:3] The higher the levels of the people in the room, the worse this
gets. Sometimes legitimately as topics discussed are sensitive, or not
worth risking bike-shedding, but often because producing a sanitised
and comprehensive summary is work no one particularly wants to do.

[fn:4] Having too many of these digests is something I deem quite
unlikely, and there are worse problems an organisation can have than
its members over-communicating.
