#+TITLE: Uses This
#+DATE: 2023-06-21

I really enjoy reading [[https://usesthis.com][uses this]] to get some ideas about what kind of
tooling other people use, and of course to borrow ideas, so I thought
I'd do my own version of this. This is also a page instead of a post,
and I will try to keep it up to date, as my setup keeps changing.

* Hardware

My workstation is optimised for portability, so everything is
relatively small and packs well for travel, while maximising
ergonomics:

- 16" M1 Apple MacBook Pro :: Brilliant computer
- [[https://www.therooststand.com/][Roost Laptop Stand]] :: Saves my neck and posture
- [[../../posts/atreus/][Keyboardio Atreus Keyboard]] :: Using the [[https://colemak.com][Colemak]] layout
- Apple Magic Trackpad :: Better for RSI (for me)
- [[https://europe.beyerdynamic.com/dt-990-pro.html][beyerdynamic DT 990 Pro]] :: Open-back, wired

* Software

Really just the current version of macOS, the [[https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/emacs/macport.nix][MacPorts version]] of
[[https://www.gnu.org/software/emacs/][Emacs]], and [[https://mozilla.org/en_US/firefox/developer/][Firefox Developer Edition]].

The specifics of my setup change a lot. I use [[https://orgmode.org/][org-mode]] for most
writing, and [[https://www.orgroam.com/][org-roam]] for organisation of notes. I have been down the
"do everything inside Emacs" road and decided that there are too many
rough edges for my taste, so I confine it to text-processing related
tasks.

All my configuration is [[https://github.com/sulami/dotfiles][available online]].

I have also gotten pretty proficient at [[https://kicad.org][KiCad]] over the last few years,
and I am slowly coming to terms with [[https://www.autodesk.com/products/fusion-360/overview][Fusion 360]].

* Dream Setup

I would like an electric standing desk. I have sat for most of my
life, but also been standing exclusively for a period of several
years. Neither seems sustainable on its own, so I think the solution
is to alternate.

Sometimes I wish for more screen estate, but realistically I do not
need it.

Desk space on the other hand is something I can never have enough of.
