#+TITLE: About

I am Robin Schroer, also known as sulami. This is my blog, where I discuss
various topics, mostly related to software development, but occasionally also
others. I am a *nix guy by heart and mainly write Clojure, Python, and Haskell.
I have been contributing to the Linux kernel as well as writing an X11 window
manager and I generally like experimenting with code.

I also love puzzles/contests, so here are some I have completed:

- Project Euler 1–100 (And a bunch more)
- The Eudyptula Kernel Challenge
- The Matasano Crypto Challenges
- Hacktoberfest 2015–2018
- Advent of Code 2015-2018
- The Monad Challenges
- The Deadlock Empire

Apart from that, I am in the 94th percentile of Functional Languages
on HackerRank, using Haskell, and in the 95th honor percentile on
CodeWars, using mostly Haskell and Python.

If you are interested in working with me, here is my [[file:cv/index.org][CV]] ([[https://blog.sulami.xyz/pages/robin-schroer-cv.pdf][PDF]]).

* Contact / Links

- Email: [[mailto:blog@sulami.xyz][blog@sulami.xyz]]
- PGP: [[file:/raw/pubkey.txt][A1418106]]
- Github: [[https://github.com/sulami][sulami]]
- Lobsters: [[https://lobste.rs/u/sulami][sulami]]
- Hacker News: [[https://news.ycombinator.com/user?id=sulami][sulami]]
