#+TITLE: Thoughts on Windows 10 and Free Software
#+DATE: 2015-06-23

Today I had a very interesting conversation about the modern software
world with a non-technical friend of mine.

Back when it happened, I considered Windows Vista a slip, they had
something new in mind, I could see the vision, but it did not work out,
which is why I never used it. Windows 7 corrected most of Vista's flaws
and was a really nice operating system for the consumer, meant as an
efficient general purpose platform usable by anyone.

I have since then made the full-time switch to *nix, meaning I have not
had Windows installed outside of a VM for about two years. I have seen
the light that is *nix, you might say. As a professional software guy, I
know just how big of a joke everything Microsoft produces is.

But anyway, after Windows 7 came Windows 8, and 8.1 which reverted some
of the disatrous changes 8 did. Still, today,
[[https://www.netmarketshare.com/operating-system-market-share.aspx][over
70% of internet users use either Windows 7 or Windows XP]], which are
known good versions. Windows 8 and 8.1 combined make up about 15%,
mostly because users despice change, and Windows 8 did not bring
neccesary new things to the table, like say
[[http://blogs.msdn.com/b/directx/archive/2014/10/01/directx-12-and-windows-10.aspx][a
new DirectX]], which not only forces core gamers to switch to Windows
10, but also comes just in time to convince developers to use it instead
of [[https://www.khronos.org/vulkan/][Vulkan]], the in my opinion better
idea, because it is not part of Microsoft's vendor lock-in.

So today I talked to this friend of mine about why people are still
using Windows, why Microsoft Office is still the standard in many
situations. We both agreed that Apple is not the saviour we are looking
for. He said, while he likes Linux from the little experience he had
with it, it is /a)/ to challenging for the average user to setup and
maybe administrate, and /b)/ too few people actually know about it as a
viable alternative. We went on to agree that the really average user
would probably be better of with a Xubuntu box, for browsing Facebook,
writing emails and watching YouTube. Maybe a bit of basic office usage.
It can do all of that just fine, and runs so much better than any
version of Windows, while arguably being more secure.

I told him that setting up something newbie-focussed like Ubuntu, Mint
or eOS is not harder than setting up Windows, assuming you can setup
Windows. Both mainly consist of clicking "Next". Of course you have to
know which harddrive you want to install to, but you have to select a
installation destination on Windows as well. Installing drivers is
usually pretty easy as well /if/ you have sort of proper hardware. Of
course there are known issues with things like
[[http://arstechnica.com/civis/viewtopic.php?f=14&t=42569][certain wifi
controller manufacturers]], and exotic hardware like DVB-cards are
usually hit or miss.

But the second point is actually more important here. Most people do not
know about Linux as an operating system they could be using. Choosing to
use Linux is actively alienating yourself. It is a whole new world, you
might have to find different programs, things might break. After all, it
is an operating system only used bu programmers and hackers, not by
ordinary non-nerds.

A subjective long time ago, Google decided to enter the emerging market
of smartphones,
[[https://en.wikipedia.org/wiki/Android_%28operating_system%29][and
chose to base their mobile operting system on the well-tested Linux
kernel]]. But they did not call it Linux, and they did not for a reason.
A lot of people do not know that they are directly using Linux every
day. More recently,
[[https://www.gamingonlinux.com/articles/steam-replaces-the-linux-tux-logo-with-steamos.5442/page=2][Valve
did the same thing]], using Linux as the basis for their
PC-console-hybrids. But it shall be called SteamOS, and just last week
or so they changed the tux icon in the Steam shop to a SteamOS one. Do
not get me wrong, I think they are doing exactly the right thing. But it
goes to show that things labeled "Linux" do not sell well.

Both he and I agreed, that once Linux adoption reaches a critical mass,
it will be very difficult to stop. There will be even more software,
especially the one that is targetet at ordinary low-tech users, more
hardware support and word will spread that you can actually use it,
people will know someone who is not a geek and still likes it. It would
no longer be conceived as a hobby. Which is why marketing divisions at
Microsoft are fighting desperately to keep things the way they are.
[[https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt][No one ever
got fired for buying Microsoft.]] It just works, except when it does
not.

Now Windows 10 is close to arriving. From my point of view it looks like
even more sh*t shoveled upon NT6, which is the trusty basis since Vista.
[[http://blog.zorinaq.com/?e=74][Microsoft has this horrible mentality
of just adding more and more without ever fixing anything]]. I guess it
is already too late to save NT6 without a rewrite. But good luck pushing
a rewrite through management.
