#+TITLE: Distractions, Productivity, and Working from Home
#+DATE: 2017-12-20

I have been working from home more than usual recently, thanks to my
employer, who understands that five days a week in an open office aren't
the ideal environment for everyone. After mentioning that I noticed a
perceived increase in productivity, I was asked to find out what it is
that makes me so much more productive at home. The obvious answer is
that there are fewer distracting factors at home than at the
office[fn:1], which of course is true, but it is not necessarily the
truth.

The reason I feel more productive when working from home, and thus
better in general, is my ability to easily get into the Zone™, the state
of mind where focus on the task at hand trumps everything else. My
objectively measured output in the form of commits can be easily gauged
by just having a look at the Github activity histogram of my account,
which shows that over the last month, the days I worked from home have
seen almost a doubling of activity. This seems like a pretty obvious
gain no one should be able to deny, but I am going to argue at this
point that there is more to my job than just pumping out code.

* What makes a great engineer?
   :PROPERTIES:
   :CUSTOM_ID: what-makes-a-great-engineer
   :END:

Sure, one part of my just is producing features and fixing bugs, but
software engineering has a huge social component many tend to forget
about. During the days I am in the office, I talk to developers from
other teams, catch up on the latest developments, discuss design
decisions for upcoming features and projects, help out in situations
that are not strictly my responsibility, and generally just trade in
some of my personal productivity to bring up company productivity. I
think it is important to make this division, because on some days I
personally do not write a single line of code, but I enable others to
sometimes save hours of their time, which arguably is the greater gain
for the company. Building a Fortress of Solitude can be tempting to
boost personal output, but it is not what makes a great engineer.

* But why?
   :PROPERTIES:
   :CUSTOM_ID: but-why
   :END:

Even after coming to the conclusion that the gain in personal
productivity might not be worth it when looking at the big picture, I
still maintain that I want to work from home some of the time. Why is
that? The gain here is personal happiness for me. My happiness is, at
least to some degree, bound to my (perceived) personal productivity.
When I track time in the evening, write my work journal[fn:2] or talk
about yesterday in the daily standup, I feel pressured to have produced
something more or less tangible. But on some days, I do not really have
anything I can say I produced. I do not think anyone actually minds,
because I just say "I spent eight hours yesterday helping someone
unbreak the builds", but somewhere deep down it still feels wrong.

Another thought I had was that I am not nearly as closely monitored when
working from home compared to the days I am coming in. This allows me to
just wander off to the kitchen, the toilet, or the supermarket if I feel
like I need a couple of minutes to think something over. This is
considerably harder to do in the office, even though our open office is
not quite an Orwellian surveillance state. Instead of taking these small
breaks, or sometimes even power naps, I just try to soldier through
while I am at the office, because that is what I am there for.

* Finding a compromise
   :PROPERTIES:
   :CUSTOM_ID: finding-a-compromise
   :END:

So what should you be doing? First of all, every situation is unique,
and I cannot give any blanket advice. If you get the chance, I think you
should definitely try working from home at some point. It does require
some discipline, more if your home is actually busy with family or
flat-mates. But do not take this opportunity for granted, and if your
employer says that this is not working out from their perspective, you
have no real alternative to accepting that fact.

Even when working from home, I make an effort to stay connected, which
today means having Slack on all my devices[fn:3] and being transparent
about what I am doing. This is an important step when building trust so
your employer does not feel like you are just abusing this privilege to
catch up on Westworld. I also only work from home when I know I am not
required in any meetings, and I make a point of talking to everyone I
need to talk to the day before, so I can tie up all loose ends.

[fn:1] This can be coworkers directly, but also just things like
       background chatter, the coffee machine, or even just visual
       distractions in the form of people walking in your field of
       vision all the time.

[fn:2] Something I have been experimenting with. More on that in a
       future post. But it's basically just writing down what I did by
       the end of the day.

[fn:3] This is in general a terrible idea, don't do this. I will write
       about information diets at some point.