#+TITLE: How to Read a Book
#+DATE: 2020-03-14

A while ago I read
/[[https://www.goodreads.com/book/show/567610.How_to_Read_a_Book][How to
Read a Book]]/, the guide to extracting information from non-fiction
books first published in 1940. Like many older books, there are parts of
it that haven't aged well, and in a particularly ironic fashion the book
is quite verbose. I thought it might be useful to compile a short and
simple step-by-step guide to efficiently reading non-fiction.

Imagine a book as an object with two dimensions: scope and detail. If
you read the entire book cover to cover, you will learn about the full
scope covered, in the level of detail of the book.[fn:1] But many books
are several hundred pages long, and active reading demands attention and
energy.

You can compromise on either of those dimensions (or both). If you just
read the first half of the book, you are compromising on scope, as there
is a whole second half of the subject you did not cover at all. If
instead you want to compromise on detail, you should read "outside-in",
starting with strategic skimming and delving in deeper afterwards.

Start by getting a vague idea of everything covered in the book, going
more and more into detail at each step. At any step you can stop and
decide if the next level of details is worth the additional time
required, but the knowledge you have extracted at that point is likely
more useful than if you had compromised on scope.

The outside-in method is also useful for picking out books to read at a
bookstore, as you can just start with the first few steps right there,
and buy the book if you want to continue.

Simply follow these steps below, as long as you feel like gaining deeper
understanding is worth the additional time. Ideally you want to have a
way of taking notes, both to capture sections or topics to investigate
further, but also to aid active reading.[fn:2]

1. Read the back cover, and any other summaries and publisher blurbs.
2. Read the table of contents, note the scope and structure. Identify
   the important and pivotal chapters.
3. Read the preface.
4. Scan the index and references for anything interesting to look at,
   both inside and outside this book.
5. Read the opening and closing parts of the pivotal chapters, usually
   about a page each.
6. Read the final part of the book containing content, such as a
   conclusion chapter or section.
7. Pick a handful of random sections throughout the whole book and read
   a page or two each.

At this point you should have spent between 30 minutes and one hour, and
have answers to these questions:

- What is the book about, and which scope does it cover?
- Are there any additional topics or works to investigate outside of its
  scope?
- Which conclusions or opinions does it offer?

The last question is particularly important if you want to continue, as
it sets the context of this book in comparison to others covering the
same subject. Authors have different backgrounds and biases, which
colour their works.[fn:3]

The more thorough levels of reading take a lot more time, but can be
useful if you want to get a deeper understanding of the subject. There
are two more steps you can take to gain more insight:

1. Continue reading the chapters, actually reading entire chapters now.
2. Use other works covering the same subject and cross-reference the
   important points as you come across them. This allows you to get
   different viewpoints on the individual points.[fn:4]

If you get this deep into a subject, the first few steps will be very
quick to perform, as you are already familiar with the subject, so you
only need to find answers to the questions above before delving in
deeper.

[fn:1] Well, not really. Performing a single, cover to cover reading
       usually does not suffice to extract everything from a book.

[fn:2] Active reading is one of these barely defined terms, but what I'm
       trying to express is the notion of thinking about the text as you
       read it, and actively trying to take in information. I might
       publish a piece on note-taking in the future.

[fn:3] A good example is David Allen's
       /[[https://www.goodreads.com/book/show/1633.Getting_Things_Done][Getting
       Things Done]]/, which does hold some value for everyone, like the
       notion of the task inbox, but also contains a lot of absurd
       examples and use-cases which clearly show the kind of life he's
       living, and the priorities he has.

[fn:4] This is what Adler calls "syntopical" reading, which is a whole
       discipline on its own. I won't cover it here, but you can find
       plenty of material online, and How to Read a Book also has a more
       detailed explanation.
