#+TITLE: Robin Uses This
#+DATE: 2017-11-11
#+PAGE: t

I really enjoy reading [[https://usesthis.com][uses this]] to get some ideas about what kind of
tooling other people use, and of course to borrow ideas, so I thought
I'd do my own version of this. This is also a page instead of a post,
and I will try to keep it up to date, as my setup keeps changing.

* Hardware

My primary computer nowadays is a specced-out 2018 15" MacBook Pro,
which is actually provided by my employer. MacOS is /alright/ and
tends to not get into the way too much.[fn:ports]

I use a stand to bring the computer up to eye level, and an Apple
Magic Keyboard and Magic Trackpad for human-machine-interfacing. I
have been using the [[https://colemak.com][Colemak keyboard layout]] for several years on all
physical keyboards due to RSI issues, and also remap caps lock to
control.

I have two sets of headphones, [[https://europe.beyerdynamic.com/dt-990-pro.html][beyerdynamic DT 990 Pro]], which sound
really nice, and [[https://www.bose.com/en_us/products/headphones/over_ear_headphones/quietcomfort-35-wireless-ii.html#v=qc35_ii_black][Bose QuietComfort 35 II]], which are noise-cancelling
and wireless.

[fn:ports] Except when the Mach kernel leaks ports, crashing user
space programs.

* Software

I use [[https://github.com/koekeishiya/yabai][yabai]] & [[https://github.com/koekeishiya/skhd][skhd]] to drive most of my desktop with the keyboard
alone.

I write basically everything in [[https://www.gnu.org/software/emacs/][Emacs]], specifically the [[https://github.com/railwaycat/homebrew-emacsmacport][Mac Port]],
which comes with some macOS-specific tweaks. [[https://github.com/sulami/dotfiles/tree/master/emacs/.emacs][My config]] is custom
written, and heavily leans on [[https://github.com/emacs-evil/evil][evil]] to emulate a vim layout. I use
[[http://isync.sourceforge.net/][isync]], [[https://notmuchmail.org/][notmuch]], and [[https://marlam.de/msmtp/][msmtp]] to fetch/tag/send email, of course from
inside Emacs. I also make heavy use of [[https://orgmode.org/][org-mode]] for both notes and to
do lists. I even write this website in it.

When it comes to browsing, my browser is currently [[https://mozilla.org/en_US/firefox/developer/][Firefox Developer
Edition]].

Worth mentioning as well is Dash, which provides offline
documentation. I always try to be as independent as possible, so I try
to have everything I need to work available offline.[fn:offline]

[fn:offline] That also includes a local copy of all my emails.

* Phone

My phone is an iPhone X, which I am quite happy with. I am not a heavy
phone user, and mainly use it to stay in contact with people.

The main software I use on my phone is [[https://beorgapp.com/][beorg]] to keep track of
everything in org-mode.
